server:
  port: 8081
  servlet:
    context-path: /api

spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 500
    scheduling:
      pool:
        size: 5
  application:
    name: ai-code-helper
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  # MySQL配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_chat_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Zhpenn1991.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: xxx
      streaming-chat-model:
        model-name: qwen-max
        api-key: xxx
      embedding-model:
        model-name: text-embedding-v4
        api-key: xxx
#        api-key: 
        api-key: 

#      openai:
#        chat-model:
#          gpt4-turbo:
#            api-key:
#            model-name: gpt-4-turbo
#          gpt3-turbo:
#            api-key: 
#            model-name: gpt-3.5-turbo
#            max-retries: 3

bigmodel:
  api-key: xxx

#logging:
#  level:
#    langchain4j: debug
# RAG配置
rag:
  documents:
    path: src/main/resources/docs
  vector:
    store:
      type: redis  # redis 或 memory
  segment:
    max-size: 800
    max-overlap: 200
  retrieval:
    max-results: 10
    min-score: 0.7

# 聊天内存配置
chat:
  memory:
    max-messages: 20


