spring:
  application:
    name: ai-code-helper
server:
  port: 8081
  servlet:
    context-path: /api
  profiles:
    active: local
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: xxx
      streaming-chat-model:
        model-name: qwen-max
        api-key: xxx
      embedding-model:
        model-name: text-embedding-v4
        api-key: xxx
bigmodel:
  api-key: xxx

#logging:
#  level:
#    langchain4j: debug