spring:
  application:
    name: ai-code-helper
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-14acdbb1803e4ba6b7c7fa1ced1dd80f
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-14acdbb1803e4ba6b7c7fa1ced1dd80f
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-14acdbb1803e4ba6b7c7fa1ced1dd80f
bigmodel:
  api-key: 30802265695244d1ac8f692eecee2537.jAlt06n0liqXBlKH
